-- +migrate Up

CREATE TABLE IF NOT EXISTS public.addresses
(
    id integer generated by default as identity
    primary key,
    building_number integer NOT NULL,
    street character varying COLLATE pg_catalog."default" NOT NULL,
    city character varying COLLATE pg_catalog."default" NOT NULL,
    district character varying COLLATE pg_catalog."default" NOT NULL,
    region character varying COLLATE pg_catalog."default" NOT NULL,
    postal_code character varying COLLATE pg_catalog."default" NOT NULL
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.addresses
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.cafes
(
    id integer generated by default as identity
    primary key,
    cafe_name character varying COLLATE pg_catalog."default" NOT NULL,
    address_id integer NOT NULL,
    rating character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT address_id FOREIGN KEY (address_id)
    REFERENCES public.addresses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cafes
    OWNER to postgres;

-- +migrate Down

DROP TABLE IF EXISTS public.cafes;
DROP TABLE IF EXISTS public.addresses;